### ISSUE TITLE
NavigationHomeScreen not found

### ISSUE THREAD

**Issue by imdarpn** [katariyanikhil/SaveIt#1]
Hey, I have clone this code and try to run that time I am getting below error :
`lib/main.dart:6:8: Error: Error when reading 'lib/screens/navigationHomeScreen.dart': No such file or directory
import 'package:saveit/screens/navigationHomeScreen.dart';`

also in code, there are no files for WhatsApp download, youtube download & TikTok downloads so I am not able to run this project

**Comment by katariyanikhil** [comment]
try re-cloning and make sure to renaming folder as "saveit" instead of SaveIt. All missing files have been uploaded.

**Comment by imdarpn** [comment]
@katariyanikhil yes working nice.
