### ISSUE TITLE
permitted error

### ISSUE THREAD

**Issue by Sedoyigit** [katariyanikhil/SaveIt#2]
![Screenshot_1597842578](https://user-images.githubusercontent.com/67701218/90638882-925e8200-e236-11ea-8ea1-69f6f4e67b90.png)

**Comment by katariyanikhil** [comment]
can you tell me in which file does the error generated during debug

**Comment by Sedoyigit** [comment]
All  download buttons

**Comment by katariyanikhil** [comment]
Make sure you check whether the Save it folder is created before pressing or on pressing the download button.

The error says that you have not given write permission make sure you check that also.

**Comment by yiss** [comment]
If you're on Android Q (10) and above you'll need to add this to the manifest ```android:requestLegacyExternalStorage="true"```

**Comment by katariyanikhil** [comment]
Thanks for the help @yiss

**Comment by gulmensedat** [comment]
I get this error on emulator, I tried it with apk on the phone, no problem
