### ISSUE TITLE
Format link 

### ISSUE THREAD

**Issue by brottobhmg** [katariyanikhil/SaveIt#3]
What format should I give to download from YouTube in the Android app?

It not works : https://youtu.be/HxOUtlUGFgo

**Comment by katariyanikhil** [comment]
Some videos which are copyrighted are not allowed to be download so it shows invalid url error.

**Comment by prannavmaytray** [comment]
You know there is an [Instagram reels downloader](https://reelit.io) that allows you to download Instagram reels with no problems.
