### ISSUE TITLE
Not Working.

### ISSUE THREAD

**Issue by EmreSURK** [katariyanikhil/SaveIt#4]
Hi,
Please specify if the project is deprecated to prevent wasting other people's time. 

Thanks.

**Comment by katariyanikhil** [comment]
What problem do you face explain or prevent wasting my time by posting anything.

**Comment by Nishant559** [comment]
The Instagram and Facebook feature is not working

**Comment by katariyanikhil** [comment]
The facebook feature only works for url starting with www.facebook.com/watch  i.e. direct video url should be provided instead of post url

I will try to update its code and update the app asap because I am busy in developing other apps
