### ISSUE TITLE
doc: how to run the app?

### ISSUE THREAD

**Issue by skywinder** [katariyanikhil/SaveIt#5]
would be nice to see some installation instruction in readme!

thanks for OS code for this, thou!

**Comment by katariyanikhil** [comment]
what kind of installation instructions do you need please let me know so I can add all of those.

**Comment by joex92** [comment]
> what kind of installation instructions do you need please let me know so I can add all of those.
> 

It would be good to have compilation and installation instructions for Android and iOS

**Comment by katariyanikhil** [comment]
It's the same as you might install a flutter app.
