### ISSUE TITLE
I got this error during the building of the project. I just downloaded and try to compile it without changing anything and got this error...

### ISSUE THREAD

**Issue by NomanBaigA** [katariyanikhil/SaveIt#6]
e: C:\Users\DELL\Desktop\onemore\SaveIt-master\android\app\src\main\kotlin\com\mmapps\flutter_app_youtube_demo\MainActivity.kt: (25, 29): Object is not abstract and does not implement abstract base class member protected/*protected and package*/ abstract fun onExtractionComplete(@Nullable p0: SparseArray<YtFile!>?, @Nullable p1: VideoMeta?): Unit defined in at.huber.youtubeExtractor.YouTubeExtractor
e: C:\Users\DELL\Desktop\onemore\SaveIt-master\android\app\src\main\kotlin\com\mmapps\flutter_app_youtube_demo\MainActivity.kt: (26, 33): 'onExtractionComplete' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
> Compilation error. See log for more details

**Comment by katariyanikhil** [comment]
Try changing android SDK versions.

**Comment by NomanBaigA** [comment]
> Try changing android SDK versions.

I tried different versions and it's useful, thanks for that. but I get some other errors
........................................................................................................................................................................

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\DELL\.gradle\caches\transforms-2\files-2.1\6b84d84e86ee0194c8eee66a1338bd63\appcompat-1.0.0\res\values-v28\values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\DELL\.gradle\caches\transforms-2\files-2.1\6b84d84e86ee0194c8eee66a1338bd63\appcompat-1.0.0\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     C:\Users\DELL\.gradle\caches\transforms-2\files-2.1\672935a6b2f1dbdf048a025004a69e66\core-1.2.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\DELL\.gradle\caches\transforms-2\files-2.1\672935a6b2f1dbdf048a025004a69e66\core-1.2.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by katariyanikhil** [comment]
I think there is a problem with gradle version try to check it and make changes in gradle as this project was made in an earlier/older version of gradle.

**Comment by NomanBaigA** [comment]
> I think there is a problem with gradle version try to check it and make changes in gradle as this project was made in an earlier/older version of gradle.

Both answers are working for me but there is one problem with that. if I try SDK version 27 or less then I face 'Android resource linking failed' full error I showed before but if I try SDK version 28 or more then I face an error related to YouTubeExtractor which I showed before.

**Comment by katariyanikhil** [comment]
Yeah, it might get you an error because some dependencies are not working on some android SDK versions. I am looking into it why its happening.

**Comment by NomanBaigA** [comment]
> Yeah, it might get you an error because some dependencies are not working on some android SDK versions. I am looking into it why its happening.

Any solution?
