### ISSUE TITLE
Download not Working (reels, post, story)

### ISSUE THREAD

**Issue by VocsyAniket** [katariyanikhil/SaveIt#8]
instaData.dart  file in userProfileData, postFromUrl, storyFromUrl  this  3 function not working downloading Url.

**Comment by katariyanikhil** [comment]
Ever since Instagram made changes to their documentation and everything, I haven't updated the code since then so It won't work as it is. I will update the repo asap.

**Comment by VocsyAniket** [comment]
> Ever since Instagram made changes to their documentation and everything, I haven't updated the code since then so It won't work as it is. I will update the repo asap.

please solve this issue ASAP, Thank you
